name: publish to Glitch
on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.authToken }}'
          project-id: '${{ secrets.projectId }}'
