name: Publish to Glitch
on:
  push

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: lonnen/sync-branch-to-glitch-action@v0.0.3
        env:
          GLITCH_GIT_URL: ${{ secrets.GlitchGitURL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BRANCH: 'main'
